### ISSUE TITLE
Support for Zeebe 1.0.0

### ISSUE THREAD

**Issue by jwulf** [camunda-community-hub/pyzeebe#132]
Zeebe 1.0.0 (roughly expected in April) contains breaking changes to the client API. 

I'm expecting these changes to be merged in the alpha2 release in March. There are more details in [this post](https://forum.zeebe.io/t/changelog-for-zeebe-client-lib-maintainers/2064).

**Comment by JonatanMartens** [comment]
Hey @jwulf, thanks for opening an issue for this!

I've opened a new issue (#136) which details some changes I want to make for `pyzeebe` 3.0.0. 

I'm closing this issue as we'll continue the conversation there.

**Comment by kbakk** [comment]
I think this issue could be kept open, to have the discussion of/track the particular breaking changes (and changes needed in Pyzeebe 3.0 to address those) in Zeebe 1.x.

**Comment by gizmo84** [comment]
I just released zeebe-grpc 1.0.0a3 (https://pypi.org/project/zeebe-grpc/1.0.0a3/) if you want to test it.

**Comment by jwulf** [comment]
1.0.0-alpha7 has a further breaking change to the gRPC API, in the `DeployProcessRequest`: https://github.com/camunda-cloud/zeebe/commit/d215dc49693581d37ed3ad0d2475794d511fed95#diff-8c4bf3af425185eccbfb2d367db259cdb026f61c45d81b59174dd552d4336305

**Comment by kbakk** [comment]
Thanks for the heads-up @jwulf. Did notice that running 1.0.0-alpha7 and later fails with pyzeebe pre-release/3.0.0 branch. 

This needs to be addressed in the dependency first though, so asked to reopen [zeebe_python_grpc#5](https://gitlab.com/stephane.ludwig/zeebe_python_grpc/-/issues/5).

**Comment by gizmo84** [comment]
Will fix it today 😉

**Comment by gizmo84** [comment]
zeebe-grpc 1.0.0rc2: https://pypi.org/project/zeebe-grpc/1.0.0rc2/
