### ISSUE TITLE
Add ability to specify an errorCode

### ISSUE THREAD

**Issue by Chadys** [camunda-community-hub/pyzeebe#162]
**Is your feature request related to a problem? Please describe.**
To be able to react to a specific business error in the workflow, you need to be able to specify the error code of an error thrown by task.

**Describe the solution you'd like**
`set_error_status` should accept an `error_code` argument (with default parameter).

Since you don't have access to the job object in the task, you won't be able to call `set_error_status` directly. But since these type of exception are part of your business logic (you handle them in your workflow), it would be practical to raise them directly from the task. Maybe by creating an exception like `BusinessError` with an error code attribute, that would automatically be handled by pyzeebe, without relying on the user writing a custom `exception_handler` for it.

**Describe alternatives you've considered**
Care must be taken not to raise an error with one of the handled error code if `set_error_status` is called with no `error_code`. I don't know what value `ThrowErrorRequest.errorCode` has when it is left unspecified (empty string?). We should agree on a value ("unhandled_error"? or whatever is default for `ThrowErrorRequest.errorCode` for retro-compatibility?) and add instruction in the documentation for the user not to use that specific value as error_code for their handled business errors.

**Additional context**
[Workflow error handling doc](https://docs.camunda.io/docs/reference/bpmn-workflows/error-events/error-events#throwing-the-error) and [ThrowError RPC](https://docs.camunda.io/docs/reference/grpc/#throwerror-rpc).

I can write the pull request for it if it is accepted

**Comment by Chadys** [comment]
I experimented a bit and this is what I found:
 - When not specifying `ThrowErrorRequest.errorCode`, it is indeed an empty string by default
 - You can't deploy a workflow containing an error event with empty error code (you get "ErrorCode must be present and not empty"), and the field won't interpret code (putting `= ""` inside will just give you the string '= ""')

This is good because this means that by keeping an empty string as default error code, users won't be able to catch it even if they want to, so there won't ever be confusion between handled and unhandled error.
Bad thing is that with current state of pyzeebe, there is no clean workaround to catch error in workflow. The only option is going low level by calling `gateway_pb2` functions directly

**Comment by kbakk** [comment]
Hi,

I am not certain, but I think you could raise your own exceptions in the tasks (your business logic), and let exceptions bubble up.

Then in the exception handler define how the various types of exceptions are returned to the Zeebe broker.

See: https://pyzeebe.readthedocs.io/en/latest/worker_tasks.html?highlight=exception_handler#task-exception-handler

**Comment by kbakk** [comment]
I do think that what you suggest sounds like a good idea, and that it would be an improvement to have such logic available by default.

**Comment by Chadys** [comment]
> Hi,
> 
> I am not certain, but I think you could raise your own exceptions in the tasks (your business logic), and let exceptions bubble up.
> 
> Then in the exception handler define how the various types of exceptions are returned to the Zeebe broker.
> 
> See: https://pyzeebe.readthedocs.io/en/latest/worker_tasks.html?highlight=exception_handler#task-exception-handler

Yes that's what I did, my exception handling is actually this:
```python
class BusinessException(PyZeebeException):
    def __init__(self, error_code: str) -> None:
        self.error_code = error_code


class WorkerExceptionHandler:
    def __init__(self, unrecoverable_exceptions=None) -> None:
        self.unrecoverable_exceptions = (
            tuple(unrecoverable_exceptions)
            if unrecoverable_exceptions
            else (BusinessException,)
        )

    def __call__(self, exception: Exception, job: Job) -> None:
        logger.exception(exception)
        if isinstance(exception, self.unrecoverable_exceptions):
            if job.zeebe_adapter:
                job.zeebe_adapter._gateway_stub.ThrowError(
                    ThrowErrorRequest(
                        jobKey=job.key,
                        errorMessage=str(exception),
                        errorCode=getattr(exception, "error_code", ""),
                    )
                )
            else:
                raise NoZeebeAdapter()
        else:
            job.set_failure_status(message=str(exception))
```
The problem here is not the exception logic (even though it would be a nice-to-have), but the need to call low-level `_gateway_stub` because `job.set_error_status` is not able to set an `errorCode`

**Comment by kbakk** [comment]
Sorry, I see that I assumed `message == code`, which isn't the case as you point out. 

I don't see any reason not to make this functionality available, so I'd say go ahead. @JonatanMartens is the maintainer though, so it's his call in the end.

**Comment by JonatanMartens** [comment]
It definitely seems like `error_code` should be an argument for `set_error_status`. 

> * You can't deploy a workflow containing an error event with empty error code (you get "ErrorCode must be present and not empty"), and the field won't interpret code (putting `= ""` inside will just give you the string '= ""')

I wonder if we should allow an empty string to be passed to `error_code`. Since zeebe doesn't allow it in a workflow definition, it would make sense to catch it beforehand in pyzeebe.

**Comment by Chadys** [comment]
It would make sense, and would encourage users to actually [handle the error on workflow's side](https://docs.camunda.io/docs/reference/bpmn-workflows/error-events/error-events/#unhandled-errors) because putting an error code makes you think about that part, so I'm all for it. But it would be a breaking change so would need to wait for pyzeebe 3.0.0.

What are your thoughts about defining a `BusinessException` (definition is in my precedent message) and having the `default_exception_handler` changed to roughly this:
```python
def default_exception_handler(e: Exception, job: Job) -> None:
    logger.warning(f"Task type: {job.type} - failed job {job}. Error: {e}.")
    error_msg = f"Failed job. Error: {e}"
    if isinstance(e, BusinessException):
        job.set_error_status(message=error_msg, error_code=e.error_code)
    else:
        job.set_failure_status(error_msg)
```

So the default behaviour already handle excepted error and task worker only need to raise it with correct `error_code`.

**Comment by kbakk** [comment]
I think the user should be able to define the `message`. I.e. when raising, use `BusinessException(message="Failed to create user", error_code="422")`. If not specified, we could resort to `f"Failed job. Error: {e}"`. 

I am not sure this needs to be a breaking change, we could just change `Job.set_error_status` and `ZeebeJobAdapter.fail_job` to have an optional `error_code` argument, defaulting to `None` and include it in the call to `GatewayStub.ThrowError` if specified.

**Comment by Chadys** [comment]
Be able to also define the message would be good.

Breaking change would happen only if we want to completely prevent the user from being able to raise a business error with no error code. Defaulting to `None` would preserve the current behaviour which is setting an error code of `""`. We can prevent the user from setting `""` directly, but if they can just use `None` to get the same behaviour it is not of much interest I think.

**Comment by kbakk** [comment]
> if we want to completely prevent the user from being able to raise a business error with no error code. 

I think it's a feature and we should allow that – it gives you certainty that a workflow won't catch the exception being thrown by the worker. Someone may use it to indicate a non-catchable error.

**Comment by asrocha** [comment]
I'm late for that, but that discussion! is exactly my use case, my django application throws exceptions with codes  and this exceptions codes are significative  for businees, like (333->fixjob not approved). I  modelling my bpmn diagrams with a (Error Catch Boundary Event), but I cant catch it, than aways mys workflow ends with a incident

**Comment by asrocha** [comment]
@Chadys, Hello !

How do you workaround that, I think in Inheritance Job class and  overwrite   set_error_status like  your previous post.
If you have solve it, please share ! I will try it in the next weekend.

**Comment by asrocha** [comment]
@Chadys , @kbakk  I 've thinking  as a valid workaround, to create a new class descendent from Worker or Job and in this class implement grpcio call to ThrowErrorRequest.

**Comment by Chadys** [comment]
@asrocha you already have a working example code of my workaround a few messages back. No need to overwrite Worker or Job, just use `exception_handler=WorkerExceptionHandler()` in your task definition and in your task execution code raise `BusinessException("333")` as necessary. I'll make a merge request as soon as I have time, in the meantime the code I provided is plenty enough to obtain the same behaviour.

**Comment by asrocha** [comment]
@Chadys  Thank you I will try it.
