### ISSUE TITLE
Why is channel not in ZeebeWorker initialization parameter?

### ISSUE THREAD

**Issue by NewAlice** [camunda-community-hub/pyzeebe#175]
**Describe the bug**
ZeebeWorker also needs 'channel: grpc.Channel = None' parameter and self.zeebe_adapter also needs channel when using secure_connection channel to set up connection
**To Reproduce**
1. Go to initialize ZeebeClient client with channel = grpc.insecure_channel(f"{hostname}:{port}") and 
ZeebeClient(hostname=hostname, port=port, channel=channel, secure_connection=True)
2. Go to initialize ZeebeWorker with only ZeebeWorker(hostname=hostname, port=port, secure_connection=True)
3. See error
E0609 13:14:33.189836000 123145442783232 ssl_transport_security.cc:1446] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
Lost connection to hostname:26500. Retrying...
E0609 13:17:33.731038000 123145442783232 ssl_transport_security.cc:1446] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
Failed to establish connection to hostname:26500. Not recoverable

**Expected behavior**
no error

**Screenshots**
![image](https://user-images.githubusercontent.com/25843983/121299756-7abccb00-c928-11eb-91c7-1627f74f461c.png)

**Additional context**
I tried to initialize ZeebeWorker object with 'channel: grpc.Channel = None' parameter and self.zeebe_adapter with channel when using secure_connection channel to set up connection, it worked well.

**Comment by JonatanMartens** [comment]
> Go to initialize ZeebeClient client with channel = grpc.insecure_channel(f"{hostname}:{port}") and
ZeebeClient(hostname=hostname, port=port, channel=channel, secure_connection=True)

This seems a little strange. You're creating an insecure channel using `grpc.insecure_channel` and then passing `ZeebeClient` `secure_connnection=True`. This means that `ZeebeClient`  will use the insecure channel created before, without looking at any other parameters passed on. So the connection to Zeebe will still be insecure.

Have you tried creating the worker without `secure_connection=True`? This would create a channel using  `grpc.insecure_channel` just like in your first example.

p.s. The `channel` argument is dropped from `ZeebeClient` in pyzeebe 3.0.0 (check out version 3.0.0rc1)

**Comment by JonatanMartens** [comment]
I'm closing this issue for now, please feel free to open it again if you have any questions.
