### ISSUE TITLE
Allow users to provide their own channel, to be able to override channel options

### ISSUE THREAD

**Issue by kbakk** [camunda-community-hub/pyzeebe#185]
**Is your feature request related to a problem? Please describe.**

To solve #178, a global config for gRPC channel was added. We have not added an API to override the config used.

We should implement a way for the user to set up a channel themself, and use that for ZeebeWorker and ZeebeClient connectivity.

**Describe the solution you'd like**

Currently, when running the worker or the client, it will implicitly set up the channel, with config based on what the user passes to the worker/client on initialization. 

We could allow the user to override the channel, e.g. by setting `zeebe_adapter.channel` on the worker/client, or having a `connect` method which takes `channel` as an optional argument.

**Describe alternatives you've considered**

1. Since it's Python, those options can be monkeypatched, but that is usually not the recommended way of changing behavior (if other options are available).
2. We can add more options to be passed in the init method for the worker/client, however that list is quite large already.

**Additional context**

I notice that on `ZeebeWorker`, the init method is IO-less, while on `ZeebeClient`, we do connect on init. The init behavior should perhaps be the same on both of these classes.

**Comment by kbakk** [comment]
@JonatanMartens I experimented with how to solve it here

https://github.com/kbakk/pyzeebe/commit/8b46e36b9c2895421efe47e19cc4b78909214efa

However, I see that the call to set up the channel is synchronous, and thus will be blocking:

https://github.com/camunda-community-hub/pyzeebe/blob/46847e1eab74e9d46c244ba8413af4bd404d7e41/pyzeebe/worker/worker.py#L61

Is that a mistake?

**Comment by JonatanMartens** [comment]
I think the worker/client should receive the channel object in their constructor or a connect method.

Like this:

```python
channel = grpc.aio.insecure_channel()
worker = ZeebeWorker(channel, max_task_count=4)
```

Or this:

```python
channel = grpc.aio.insecure_channel()
worker = ZeebeWorker(max_task_count=4)
worker.connect(channel)
```

We could then provide some standard channel creation flows:

```python
def create_insecure_channel(hostname: str = "localhost", port: int = 26500, grpc_options: Optional[Dict] = None) -> grpc.aio.Channel: ...
def create_camunda_cloud_channel(client_id: str, client_secret: str, cluster_id: str, grpc_options: Optional[Dict] = None) -> grpc.aio.Channel: ...
```

This way we don't require users to write everything from scratch each time, but we allow them to create their own channel and inject it.

**Comment by JonatanMartens** [comment]
> @JonatanMartens I experimented with how to solve it here
> 
> [kbakk@8b46e36](https://github.com/kbakk/pyzeebe/commit/8b46e36b9c2895421efe47e19cc4b78909214efa)
> 
> However, I see that the call to set up the channel is synchronous, and thus will be blocking:
> 
> https://github.com/camunda-community-hub/pyzeebe/blob/46847e1eab74e9d46c244ba8413af4bd404d7e41/pyzeebe/worker/worker.py#L61
> 
> Is that a mistake?

The `connect` method has no async calls, so there is no reason to make it async (currently).

**Comment by JonatanMartens** [comment]
> I notice that on ZeebeWorker, the init method is IO-less, while on ZeebeClient, we do connect on init. The init behavior should perhaps be the same on both of these classes.

Agreed. I believe the reason for this was that I didn't want the `ZeebeClient` class to connect on every call. This would be solved by injecting the channel object.

**Comment by kbakk** [comment]
I was thinking we could add a decorator that ensures that the client is connected before running the method:

```python
def _connect(method):
    @wraps(method)
    def _connect_wrapper(self, *args, **kwargs):
        if not self.zeebe_adapter.connected:
            self.connect()
        return method(self, *args, **kwargs)
    return _connect_wrapper
```

**Comment by kbakk** [comment]
> Or this:
> 
> ```python
> channel = grpc.aio.insecure_channel()
> worker = ZeebeWorker(max_task_count=4)
> worker.connect(channel)
> ```

I prefer this approach, as the `ZeebeWorker` already takes many arguments, I think we should avoid adding another.

But I also like that you can start a worker without configuring the channel, I think we should keep that functionality. So the user can run either 

```python
worker = ZeebeWorker(hostname="zeebe")
... # set up task
worker.work()
```

And be able to set up a channel:

```python
... # prepare channel
worker = ZeebeWorker()
... # set up task
worker.connect(channel)
worker.work()
```
