### ISSUE TITLE
Can you add to documentation example how to call worker.stop() in "async pyzeebe 3.0.0"

### ISSUE THREAD

**Issue by tomas-zemres** [camunda-community-hub/pyzeebe#195]
We are trying to use Zeebe 1.1.0 with pyzeebe 3.0.0rc3,

and we want to add signal handler on SIGTERM that calls worker.stop().
But we don't know how to correctly call "worker.stop()" that is "async def" from the signal handler.

Is it possible add simple example that uses "worker.stop()" to documentation for "async" pyzeebe 3.0.0, please?

**Comment by JonatanMartens** [comment]
I've added an example to the docs.
You can check it out here: https://pyzeebe.readthedocs.io/en/pre-release-3.0.0/worker_quickstart.html#stopping-a-worker :)

**Comment by tomas-zemres** [comment]
Thank you for update docs.

There is example including correctly used signal handler:

```
import asyncio
import signal
from pyzeebe import ZeebeWorker, create_insecure_channel

async def main():
    channel = create_insecure_channel("zeebe", port=26500)
    worker = ZeebeWorker(channel)

    @worker.task(task_type="my_task")
    async def my_task(x: int): 
       return {"y": x + 1}

    def interrupt_handler(*args, **kwargs):
        async def stop_worker():
            print("stopping...")
            await worker.stop()
        asyncio.create_task(stop_worker())

    asyncio.get_event_loop().add_signal_handler(signal.SIGINT, interrupt_handler)

    await worker.work()
    print("end of main")


asyncio.run(main())               

```
