### ISSUE TITLE
No exception text when ZeebeBackPressureError is raised

### ISSUE THREAD

**Issue by Andy-JB** [camunda-community-hub/pyzeebe#205]
**Describe the bug**

When job_poller.py attempts to activate jobs, if a `ZeebeBackPressureError` is raised, no exception text will be logged.

Current log text is `Exception: . Retrying in 5 seconds...`

**To Reproduce**
1. In job_poller.py, change the `try` statement for `poll_once` to
```
try:
    raise ZeebeBackPressureError()
```
2. Start the worker

**Expected behavior**
`Failed to activate jobs from the gateway. Exception: ZeebeBackPressureError(). Retrying in 5 seconds...`

This can be achieved  by changing

 `logger.warning(f"Failed to activate jobs from the gateway. Exception: {str(error)}. Retrying in 5 seconds...")`

to

 `logger.warning(f"Failed to activate jobs from the gateway. Exception: {repr(error)}. Retrying in 5 seconds...")`

**Desktop (please complete the following information):**
 - OS: IOS
 - 3.0.0rc2, Zeebe 1.1.0

**Comment by JonatanMartens** [comment]
Fixed in the next pre-release. Thanks for bringing this to my attention
