### ISSUE TITLE
Expected Job.variables to contain the variables in a task

### ISSUE THREAD

**Issue by jelleklaver** [camunda-community-hub/pyzeebe#207]
**Is your feature request related to a problem? Please describe.**
When #176 was introduced, it also introduced some expected behaviour (to me at least ;-)). I expected when using the `pyzeebe.Job` for a parameter on a task, all variables would be replaced by the job (since it contains a variables dictionary). Therefore, I tried to do something like the following:

```py
@worker.task('create_organisation')
def create_organisation(job: pyzeebe.Job):
    """Create organisation from job.variables"""
    organisation = job.variables["organisation"]
    # do something with organisation
    job.variables['new_var'] = new_var
    return job.variables
```

However, this doesn't work, since the `job.variables` dict doesn't actually contain the variables, but it recursively contains the job.

**Describe the solution you'd like**
I think it would be best to have access to the actual variables through `job.variables`, if possible. Else, the variables should be removed of this 'kind of Job' (maybe related to #179). But at the very least, I think it should be clearly stated in the docs if this behaviour is kept.

**Describe alternatives you've considered**
You can still get the variables the regular way.

E.g. this does work:
```py
@worker.task('create_organisation')
def create_organisation(job: pyzeebe.Job, organisation):
    """Create organisation from job's variables"""
    # do something with organisation
    return {'new_var': new_var}
```

**Additional context**
Version used: v3.0.0rc3

**Comment by JonatanMartens** [comment]
Fixed in v3.0.0rc4
