### ISSUE TITLE
Zeebe worker does not continue to process tasks after Zeebe is restarted

### ISSUE THREAD

**Issue by ivanmerxx** [camunda-community-hub/pyzeebe#213]
Hello, when the Zeebe is restarted the Zeebe worker ends with an error. Is it an expected behaviour or it should continue to process the tasks after the Zeebe is up again?

i use pyzeebe client version v3.0.0rc3

**To Reproduce**
Start zeebe + zeebe worker
Stop zeebe
Worker ends with an exception:
`grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.CANCELLED
	details = "Received RST_STREAM with error code 8"
	debug_error_string = "{"created":"@<masked>","description":"Error received from peer ipv4:<maskedip>","file":"src/core/lib/surface/call.cc","file_line":<masked>,"grpc_message":"Received RST_STREAM with error code 8","grpc_status":1}"`

**Possible fix**
Start catching the exception as the ones in the job_poller.poll_once where the ZeebeBackPressureError, ZeebeGatewayUnavailableError, ZeebeInternalError are.

**Comment by JonatanMartens** [comment]
Fixed in v3.0.0rc4
