### ISSUE TITLE
Set job success status before "after" decorator runs

### ISSUE THREAD

**Issue by Andy-JB** [camunda-community-hub/pyzeebe#294]
I think the status of a job should be set to "success" before the "after" decorator runs. That way, the decorator can log that the job has completed.

ie swap lines 37 and 38:

https://github.com/camunda-community-hub/pyzeebe/blob/570f95a097accfef25f77a134bcfd6af888375eb/pyzeebe/task/task_builder.py#L30-L40

**Comment by JonatanMartens** [comment]
Setting the status to "success" before running the decorators would probably break some usages.

Consider this scenario:

```python
def add_metadata_decorator(job):
    job.variables["metadata"] = my_metadata
    return job
```

Setting the job to success before running the decorator would mean that the gateway doesn't receive the `metadata` variable.

I think we should introduce a new status to the `JobStatus` enum. Something like `RunningAfterDecorators` or `CompletedJob`
