### ISSUE TITLE
Getting empty job variables when using job: Job in worker

### ISSUE THREAD

**Issue by nilsonrossi** [camunda-community-hub/pyzeebe#311]
According to the doc, i can define in worker parameters, the variable `job: Job`, so we can get the Job instance.
However, the `job.variables` is always empty and i think the error is when pulling the jobs:

https://github.com/camunda-community-hub/pyzeebe/blob/7700d0a37edaef42b8aa28f505b3d3c637b2d33a/pyzeebe/worker/job_poller.py#L54-L61

The variable `self.task.config.variables_to_fetch` in this case is `['job']`. This mean that, if there isn't a `job` variable in the instance variables, the worker will receive a Job with an empty variables.

**How to reproduce:**
- Just create a worker with `job: Job` as parameter, and `print(job.variables)` inside the function.
- Run a new process passing some data in variables.
```
@worker.task(task_type="task_1")
def task_1(job: Job):
    print(job.variables)
    return {}
```

If i run a new process with `{"var1": "value"}` variable, the worker should print exact the same variables.Sorr
Sorry about the English if i made some mistakes.

**Comment by dimastbk** [comment]
fixed in #404
