### ISSUE TITLE
Update zeebe-grpc to 8.0.4

### ISSUE THREAD

**Issue by Andy-JB** [camunda-community-hub/pyzeebe#322]
**Is your feature request related to a problem? Please describe.**
While it is still compatible with Camunda 8, Pyzeebe has not been updated to support Zeebe v8.0.4

**Describe the solution you'd like**
Update Pyzeebe to support Zeebe v8.0.4

**Additional context**
This would also contribute to fixing #305

**Comment by Benjoyo** [comment]
Hey @JonatanMartens, any chance to get this project up-to-date again? Maybe some other people can help with maintenance, like approving PRs if you don't have the time?
