### ISSUE TITLE
All variables from process are injected into a task function that takes in no parameters

### ISSUE THREAD

**Issue by DanielEidlin** [camunda-community-hub/pyzeebe#337]
**Describe the bug**
When you create a function that doesn't take any parameters in its signature, all the variables from the process scope are passed into it.
The workaround I used to solve this is to take in `*args, **kwargs` inside the task function signature.

**To Reproduce**
1. Create a task function that takes in no parameters.
2. Run a process which uses that task in it.
3. Code crashes from an unexpected parameters error.

**Expected behavior**
No variables should be injected and the function should complete normally.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.4

**Comment by ohasi** [comment]
Hey, took a knack at fixing it - #348.
