### ISSUE TITLE
This project is still actively maintained 

### ISSUE THREAD

**Issue by micudaj** [camunda-community-hub/pyzeebe#346]
Hello,

I was wondering if this project is still active and still maintained as the last release was in April 2022 and e.g. a PR for raising zeebe-grpc 8.0.4 is still open. As we are actively using this library and I was wondering what the official state of this repository is. Can you please comment on that? We are currently evaluating our options regarding connecting to Zeebe in Camunda 8 using Python code.

Thank you in advance for any information!

**Comment by JonatanMartens** [comment]
Hey, @micudaj.

I've been quite busy this past year, so this project has been less active.
I hope this changes in the coming months, meaning I will have more time to invest in pyzeebe.

I'm not planning on dropping maintenance in any way, shape, or form.

I hope that clears things up!

**Comment by micudaj** [comment]
Hi @JonatanMartens,

Thank you very much for your clarification! Happy to hear that! Would you be open to having additional people help you maintaining this project?

**Comment by xomiamoore** [comment]
Hey there @micudaj, we are now looking for additional maintainers, if you are still interested https://github.com/camunda-community-hub/pyzeebe/issues/381
