### ISSUE TITLE
When running process return all metadata, not just process_instance_key

### ISSUE THREAD

**Issue by hoou** [camunda-community-hub/pyzeebe#360]
**Is your feature request related to a problem? Please describe.**
We want to log and store the version of the created process instance when calling `run_process`. At the moment, it's not possible since the `run_process` function returns only `process_instance_key: int`. We had to hack it (patch it) in our codebase to get all relevant info from Zeebe API.

**Describe the solution you'd like**
It's not hard to implement, as Zeebe API already provides all the necessary info, [documentation here](https://docs.camunda.io/docs/apis-tools/grpc/#createprocessinstance-rpc), namely: `process_instance_key`, `process_definition_key`, `version` and `bpmn_process_id`. For some reason, the current implementation in `pyzeebe` currently takes only `process_instance_key` from the bigger response and passes it further.

I already have the solution prepared. Plz check it out and give me your feedback: [my forked repo](https://github.com/camunda-community-hub/pyzeebe/compare/master...hoou:pyzeebe:master)

**Describe alternatives you've considered**
I considered hitting Operate API every time after we create a process instance, but that is stupid, slow, inefficient, doesn't make sense, and Operate API can be down.

**Additional context**
I'm the first-time contributor here, so plz bear with me :D 

Also, what I'm struggling with is the version of the package. According to the `semver` versioning, it should be a major version change (3->4) because of breaking change - I'm changing the response of existing functions. So either you're OK with that, and we will bump the major version, or I would have to implement a backward-compatible solution (probably new functions), which will bump a minor version (adding a new feature). Wdyt?

**Comment by gevezex** [comment]
+1 to this
