### ISSUE TITLE
The dbt-snowflake requires >=4.0.0 while pyzeebe has dependency on <4.0, making it impossible to use dbt with camunda

### ISSUE THREAD

**Issue by arijaleagle** [camunda-community-hub/pyzeebe#361]
https://github.com/camunda-community-hub/pyzeebe/blob/6a56c799f18f048b7696a7fa80623c37013dfd4d/poetry.lock#L1368

dbt-core (1.6.4) depends on protobuf (>=4.0.0)
 and dbt-core (1.6.5) depends on protobuf (>=4.0.0), dbt-core (>=1.6.0,<1.7.0) requires protobuf (>=4.0.0).
    And because pyzeebe (>=3.0.4) requires protobuf (>=3,<4) (1), pyzeebe (>=3.0.4) is incompatible with dbt-core (>=1.6.0,<1.7.0)

**Comment by xomiamoore** [comment]
@JonatanMartens, any insight here?

**Comment by arijaleagle** [comment]
Last few branches failed, otherwise, I would have attempted to upgrade the version. we just need to use  "zeebe-grpc"
with version = 8.2.1 instead of "8.0.4.post1". The newer version https://pypi.org/project/zeebe-grpc/#data depends on protobuf 4.21.

Thank you
