### ISSUE TITLE
Does this library work with Camunda Self-Hosted?

### ISSUE THREAD

**Issue by paselin-vf** [camunda-community-hub/pyzeebe#365]
I've been trying to get it to work with the on-premise set up and haven't been successful. The simple solution might be to distribute a certificate/key to the Zeebe Gateway and use that with my worker. Thoughts or guidance on this would be appreciated since the library appears to be tailored to the cloud offering. Thanks!

**Comment by mashkovd** [comment]
Hello, I found only following [channel](https://github.com/camunda-community-hub/pyzeebe/tree/master/pyzeebe/channel)

1. [camunda_cloud_channel.py](https://github.com/camunda-community-hub/pyzeebe/blob/master/pyzeebe/channel/camunda_cloud_channel.py)
2. [insecure_channel.py](https://github.com/camunda-community-hub/pyzeebe/blob/master/pyzeebe/channel/insecure_channel.py)
3. [secure_channel.py](https://github.com/camunda-community-hub/pyzeebe/blob/master/pyzeebe/channel/secure_channel.py)

In my case i have insecure_channel with OAuth
![image](https://github.com/camunda-community-hub/pyzeebe/assets/1842423/82abfa71-de90-498d-be73-8cdff6f4c610)


I try use camunda_cloud_channel as base for my custom channel but have problems with using insecure_channel and def [**_create_camunda_cloud_credentials**](https://github.com/camunda-community-hub/pyzeebe/blob/6a56c799f18f048b7696a7fa80623c37013dfd4d/pyzeebe/channel/camunda_cloud_channel.py#L47)

Can you try connection to insecure zeebee with OAuth
