### ISSUE TITLE
Auth token renewal

### ISSUE THREAD

**Issue by vincentgiraud** [camunda-community-hub/pyzeebe#385]
**Is your feature request related to a problem? Please describe.**
Once the oauth token expired, an "unauthenticated" grpc exception will be raised: "Failed to parse bearer token, see cause for details"

**Describe the solution you'd like**
I'd like a coroutine (or else) to renew the token with or without recreating the channel hence the worker.

**Describe alternatives you've considered**
Catching the exception and calling again the main function

**Comment by dimastbk** [comment]
For inspiration: https://github.com/googleapis/google-auth-library-python/blob/32ed6015ea71f9dd1a594b3caa88fd328f56b0b7/google/auth/transport/grpc.py#L37
