### ISSUE TITLE
Token renewal still broken on create_camunda_cloud_channel

### ISSUE THREAD

**Issue by PSanetra** [camunda-community-hub/pyzeebe#498]
https://github.com/camunda-community-hub/pyzeebe/issues/385 is still occuring when `create_camunda_cloud_channel` is used. I guess the new `CamundaIdentityCredentials` should be used here.

Version: [v4.0.0rc6](https://github.com/camunda-community-hub/pyzeebe/releases/tag/v4.0.0rc6)

**Comment by dimastbk** [comment]
Should be fixed in https://github.com/camunda-community-hub/pyzeebe/pull/468

**Comment by felicijus** [comment]
@PSanetra Please test it again with the changes in #468.

**Comment by dimastbk** [comment]
Fixed in #468
