### ISSUE TITLE
Use environment variables to configure Zeebe

### ISSUE THREAD

**Issue by kbakk** [camunda-community-hub/pyzeebe#81]
**Is your feature request related to a problem? Please describe.**
The zeebe-client-node library has a "[Zero-Conf constructor](https://github.com/zeebe-io/zeebe-client-node-js#zero-conf)" that allows to use environment variables to set up Zeebe. 

This project could benefit from taking the same approach. 

It already supports specifying `hostname:port` with `ZEEBE_ADDRESS`. 

**Describe the solution you'd like**
To quote from zeebe-client-node docs:

> With no relevant environment variables set, it will default to localhost on the default port with no TLS.
> 
> The following environment variable configurations are possible with the Zero-conf constructor:
> 
> Camunda Cloud:
> 
> ```
> ZEEBE_ADDRESS
> ZEEBE_AUTHORIZATION_SERVER_URL
> ZEEBE_CLIENT_SECRET
> ZEEBE_CLIENT_ID
> ```
> 
> Self-hosted or local broker (no TLS or OAuth):
> 
> ```
> ZEEBE_ADDRESS
> ```
> 
> Self-hosted or local broker with OAuth + TLS:
> 
> ```
> ZEEBE_CLIENT_ID
> ZEEBE_CLIENT_SECRET
> ZEEBE_TOKEN_AUDIENCE
> ZEEBE_AUTHORIZATION_SERVER_URL
> ZEEBE_ADDRESS
> ```
> 
> Basic Auth:
> 
> ```
> ZEEBE_BASIC_AUTH_PASSWORD
> ZEEBE_BASIC_AUTH_USERNAME
> ```

**Describe alternatives you've considered**
- Having a function that's responsible for loading config and pass it to ZeebeWorker/ZeebeClient on instantiation.

E.g.

```py
zeebe_client = ZeebeClient(**get_zeebe_config())
# where `get_zeebe_config` would return a dict
# e.g. {"secure_connection": True, "hostname": "localhost", "port": 26500}
```

---

If this is a direction we'd like to take, I'd be happy to submit a PR for this.

**Comment by JonatanMartens** [comment]
I definitely think this is something that we want in pyzeebe. It would be great if you could submit a PR.

**Comment by JonatanMartens** [comment]
Should I add this issue to the Pyzeebe 3.0.0 milestone @kbakk?

**Comment by kbakk** [comment]
@JonatanMartens I assume #186 was accidentally closed (because the branch it was made against was deleted)? Should I try to rebase this against master/development?

**Comment by JonatanMartens** [comment]
@kbakk, sorry for the late response. 

It would be great if you could rebase this agains master :)
